### PR TITLE
Zootoolsets icons

### PR DESCRIPTION
**Pull request by keenfoong**
New icons for zoo toolsets.

### CODE REVIEW

**Comment by keenfoong** [comment]
Should these icons be placed in zoocore or put in the zoo toolsets repo?

**Comment by dsparrow27** [comment]
Are they being used by non toolsets? eg. hive?

**Comment by keenfoong** [comment]
At the moment they're only used in zoo toolsets

**Comment by dsparrow27** [comment]
Move it to that repo then

**Comment by keenfoong** [comment]
Ok cool

**Pull request closed without merging**
